本プログラムは、日本の主要6地点（札幌、仙台、東京、大阪、福岡、那覇）における気温偏差データの相関を分析し、「日本列島全体の気温変動に共通して見られる主要なパターン」を数理的に抽出することを目的としている。

In [1]:
import numpy as np

In [2]:
#データを読み込む
#6地点（札幌、仙台、東京、大阪、福岡、那覇）の気温偏差データが含まれるファイルをロード
ds = np.load('jp_tempa.npz')
#各地点の時系列データ（偏差）を抽出
sapporoa = ds['sapporoa']
sendaia = ds['sendaia']
tokyoa = ds['tokyoa']
osakaa = ds['osakaa']
fukuokaa = ds['fukuokaa']
nahaa = ds['nahaa']

# データの長さ（月数）を取得
N = tokyoa.shape[0]
#Nヶ月分の6地域の気温変化時系列を縦に並べた6行N列の行列
X = np.array([sapporoa,sendaia,tokyoa,osakaa,fukuokaa,nahaa])
# 行列Xとその転置行列の積をサンプル数Nで割り、共分散行列Cを求める
C = X@X.T/N

#共分散行列Cに対して固有値分解を行い、固有値Lamと固有ベクトルEを算出
[Lam,E] = np.linalg.eig(C)

#固有値が分散の大きさに対応するため、寄与率の高い順に並び替える
index = Lam.argsort()[::-1] #降順のインデックスを取得
Lam = Lam[index] #固有値を並び替え
E = E[:,index] #対応する固有ベクトル（主成分ベクトル）を並び替え

#固有値を対角成分に持つ行列Lを作成
L = np.diag(Lam)

#E：各列が主成分ベクトル（各地点の重み係数）
print(E)
#L：対角成分が各主成分の固有値（分散の大きさ）
print(L)

[[ 0.44160822  0.57741057  0.59540159  0.27065196 -0.19822274  0.06731586]
 [ 0.49813022  0.22818016 -0.13500691 -0.50577387  0.64515367 -0.09768713]
 [ 0.45849685  0.00738671 -0.46963208 -0.26566293 -0.60907616  0.35724112]
 [ 0.41860849 -0.27739414 -0.12446413  0.25524364 -0.17195488 -0.79850504]
 [ 0.39251509 -0.46074036 -0.02679247  0.54072887  0.34901006  0.46769291]
 [ 0.13163564 -0.57030438  0.6249053  -0.49277429 -0.14877573  0.04424494]]
[[4.11137178 0.         0.         0.         0.         0.        ]
 [0.         1.12522589 0.         0.         0.         0.        ]
 [0.         0.         0.41433637 0.         0.         0.        ]
 [0.         0.         0.         0.25076139 0.         0.        ]
 [0.         0.         0.         0.         0.1247215  0.        ]
 [0.         0.         0.         0.         0.         0.0963357 ]]
